#!/usr/bin/perl -w

use strict;
use warnings;
use Date::Parse;
my $self = {@ARGV};
my $output = 0;

my $help = "Enter something like time hh, time hh:mm, time hh:mm:ss";
if (!defined $self->{time} ){die "No time param specified. $help";}

if ($self->{time} =~ m/:/){
	my ($ss,$mm,$hh,$day,$month,$year,$zone) = strptime($self->{time});
	$output = $ss if (defined $ss);
	$output = $output + ($hh*60*60) if (defined $hh);
	$output = $output + ($mm*60) if (defined $mm);
} else{
	$output = $output + ($self->{time}*60*60)
}
if (($output==0) || (($self->{time} =~ tr/://)>2)){die "Invalid time format. $help"}
print $output;
