#!/bin/bash

while :
do

	CHANNEL="$1";
	URL="";
	OUTPUT="rtp://239.255.1.1:5004"
	if [ "$CHANNEL" = "tvm" ]; then
		URL="$(./tvm_live_stream.sh tvm)";
	elif [ "$CHANNEL" = "tvm2" ]; then
		URL="$(./tvm_live_stream.sh tvm2)";
		OUTPUT="rtp://239.255.1.2:5004"	
	else
		URL="$(./tvm_live_stream.sh tvm)";
		CHANNEL="tvm";
	fi

	if [ "$URL" = "" ]; then
		echo "feed inactive, pausing for 3 minutes.";
		sleep 180;
	else
		ffmpeg -hide_banner -loglevel warning -t 8:00:00 -re -i "${URL}" -c copy -f rtp_mpegts ${OUTPUT}
		echo "playlist expired, resetting feed";
		sleep 60;
	fi
done


