#!/bin/bash

while :
do

	CHANNEL="$1";
	URL="";
	OUTPUT="rtp://239.255.1.1:5004"
	if [ "$CHANNEL" = "tvm" ]; then
		URL=";$(./tvm_live_stream.sh tvm)";
	elif [ "$CHANNEL" = "tvm2" ]; then
		URL="$(./tvm_live_stream.sh tvm2)";
		OUTPUT="rtp://239.255.1.2:5004"	
	else
		URL="$(./tvm_live_stream.sh tvm)";
		CHANNEL="tvm";
	fi

	ffmpeg -hide_banner -loglevel warning -t 8:00:00 -re -i "${URL}" -c copy -f rtp_mpegts ${OUTPUT}
#	ffmpeg -hide_banner -loglevel warning -re -t 8:00:00 -i $(./tvm_live_stream.sh) -c:v libx265 -preset fast -crf 28 -tag:v hvc1 -c:a eac3 -b:a 224k -f rtp_mpegts  rtp://239.255.1.1:5004
	sleep 10;
	echo "resetting feed";
done


